"""make jti unique in jwt blacklist table

Revision ID: 1ea3f253f6c5
Revises: 37766ce1f16d
Create Date: 2026-03-11 21:33:06.760737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea3f253f6c5'
down_revision: Union[str, Sequence[str], None] = '37766ce1f16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jwt_blacklist', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['jti'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jwt_blacklist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
